databases:
  - name: atlascrm-db
    databaseName: atlascrm
    user: atlascrm
    plan: free

services:
  - type: web
    name: atlascrm
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: atlascrm-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
